sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null; # intall on travis instance 
  - source $HOME/google-cloud-sdk/path.bash.inc # looks at default directory of sdk install, apply config from file
  - gcloud components update kubectl # install kubectl command
  - gcloud auth activate-service-account --key-file service-account.json # google cloud auth