# file to tell issuer where to get certificate from
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "lloydnoone92@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-prod # not the actual secret for certificate, just something letsencrypt uses at this point
    solvers:
      - http01:
          ingress:
            class: nginx